confluence:
  base_url: "https://your-company.atlassian.net/wiki"  # Replace with your actual URL
  username: "your.email@company.com"  # Replace with your email
  api_token: "your-api-token-here"  # Replace with your API token
  space_key: "TSS"

local:
  markdown_dir: "./test-docs"
  exclude:
    - "README.md"