name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  GO111MODULE: "on"
  GOPATH: "${{ github.workspace }}/go"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Install dependencies
        run: |
          go get ./...

      - name: Run tests
        run: make test

      - name: Upload Codecov (optional)
        if: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'

      - name: Run tests and generate coverage
        run: |
          go test ./... -coverprofile=coverage.txt

      - name: Upload coverage to Codecov
        if: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          fail_ci_if_error: true
